### ISSUE TITLE
Add javascript one-liners

### ISSUE THREAD

**Issue by brainless-coder** [brainless-coder/Algorithms#4]

**Comment by ChoukseyKhushbu** [comment]
Can I contribute to this issue?

**Comment by brainless-coder** [comment]
@ChoukseyKhushbu I have assigned you this issue, go ahead

**Comment by ChoukseyKhushbu** [comment]
Created #9 PR for this.
Please check @brainless-coder

**Comment by brainless-coder** [comment]
great work @ChoukseyKhushbu I am closing this issue as i have merged your PR now
